opencb/iva

src/index.html

Validation form in variant-analysis-upload

Feature analysis

---

src/config.js
src/iva-app.html

form validation in jsorolla dependency (variant-analysis-upload)

jsorolla dependency upgraded

---

src/config.js

variant-clinical-upload-webcomponent modified: two main parts are distinguished in the form. One related to attributes related to individuals and another related to a variable set.
clinical attributes in config.js are modified

jsorolla depdency upgraded. clinical attribute modified in config.js

---

src/conf/config.js
src/conf/tools.js
src/index.html

- opencga-family-webcomponent: pedigreeRender function is called when input text related to family name changes
- improvements in variant-clinical-upload and variatn-clinical-samples

Improvements in web-components

---

src/conf/tools.js

- LifeStatus has been added to variant-clinical-upload
- FILTER has been added to attributes in clinical analysis so that is its known whether a prioritization has been run for an analysis.

New field in variant-clinical-upload. FILTER attribute in clinical analysis

---

bower.json
src/conf/config.js
src/index.html

- Several issues have been changed for generating an HTML report for a given analysis.
- Changes in components related to the selection of analysis 
- jsPDF and html2pdf dependencies included in bower.json and index.html

Several changes in web components related to report

---

src/index.html
src/iva-app.html

The following tasks have been achieved:
- Migration of variant-clinical-upload webcomponent to Polymer2
- Use of PolymerUtils in variant-clinical-upload
- Migration of opencga-message-dialog  to Polymer2
- Use of PolymerUtils in opencga-message-dialog
- Fixes in PolymerUtils.js

Polymer 2.0

---

src/conf/config.js
src/index.html
src/iva-app.html

- New path for PolymerUtils.js
- variant-clinical-samples.html web component migrated to polymer 2

Upgrade to polymer 2.0

---

src/index.html
src/iva-app.html
src/jso-styles.html
src/welcome.html

Several Jsorolla web components have been migrated to Polymer 2.0

Migration to Polymer 2.0

---

src/index.html
src/iva-app.html

- Migrated Variant-facet
- Migrated Variant-beacon
- Added new methods to PolymerUtils

Upgraded Jsorolla dependency

---

.eslintrc.json
src/conf/config.js
src/conf/tools.js
src/iva-app.html

Pull request related to opencb/iva#125

Performance improvements

---

.eslintrc.json
src/components/iva-settings.html
src/conf/config.js
src/index.html
src/iva-app.html

- Alignments in prioritization is working now.
- new config eslint
- Refactor PolymerUtils to UtilsNew
- Resolved issue opencb/iva#128

Alignments, Utilsnew, eslint and issue opencb/iva#128

---

src/conf/config.js
src/iva-app.html

- genome-browser: study is dynamic now
- eslint warnings and errors in variant-genome-browser
- Refactor const bioType to biotype related to opencb/iva#128

Several refactor 

---

Gruntfile.js

- New replace task for gruntfile to switch every [[importPath]] to [[rootPath]]
- Some improve in HPO input.

GruntFile and HPO

---

src/conf/config.js
src/conf/tools.js
src/index.html
src/iva-app.html
src/test/index-dev.html

Create new index-dev for develop and index to with dist folder.

New index for develop

---

README.md
build-vendors.js
post-replace-iva.js
src/prod/index.html

We have updated Readme instructions to build iva with npm and we have fixed icons errors in build folder.

Update Readme and fixes in build

---

src/conf/tools.js
src/iva-app.html
src/prod/index.html

Upgrade JSorolla dependency. 
Added new config in tools for tooltips.

Upgrade JSorolla

---

package.json
src/index.html
src/iva-app.html
src/prod/index.html

Added notify dependency.
Added validation in login inputs.
Upgrade JSorolla dependency

Added Notify and validation in login

---

src/conf/tools.js

Some sections and subsections added to tools.js

Feature menu filter

---

src/conf/config.js
src/conf/tools.js
src/index.html
src/iva-app.html
src/prod/index.html
src/utils/utilsApp.js

- We added token refresh feature.
- We made some improvements related to previous Pull Requests.
This closes #157

Added refresh token and fix improvements

---

src/conf/config.js
src/conf/tools.js
src/index.html
src/iva-app.html

- Added new item Panel to menu.
- Added Panel browser and panel editor merged from panel-editor branch.
- Created  3 tabs for automatic mode in variant-prioritization clinical

Created panel browser and editor
